print("My name is", "Python.", end=" ")
print("Monty Python")
print()
print("My name is ", end="")
print("Monty Python")
print()
print("My", "name", "is", "Monty", "Python", sep="-")
print()
print("My", "name", "is", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")
